### ISSUE TITLE
Create a 2D prototype of the location tracking

### ISSUE THREAD

**Issue by mgood13** [enoch-chang/urosolutions-project#12]
1. Build the Arduino set up of the location tracker
2. Add a second sensor and develop the algorithm to create a 2D map with the two sensors

**Comment by mgood13** [comment]
- [x] Research competitive devices

- [x] Create Arduino Sketch for distance tracking

- [x] Create 2D board for distance tracking calibration

- [x] Create circuit design for multi-dimensional tracking

- [ ] Derive equation for 2D position
